site_name: Persona 4 Golden Modding Docs
site_dir: ../sites/p4g
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: orange
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
