site_name: Persona 5 Royal Modding Docs
site_url: https://personadocs.github.io/p5r
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode