site_name: Persona 3 FES Modding Docs
site_dir: ../sites/p3f
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
